# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

party2 = Party.create({party: 'raviolis'})
party3 = Party.create({party: 'grandma'})
party4 = Party.create({party: 'squashy'})
party5 = Party.create({party: 'laz-and-chaz'})
party6 = Party.create({party: 'the-gs'})
party7 = Party.create({party: 'tiocarlo'})
party8 = Party.create({party: 'claire'})
party9 = Party.create({party: 'yeesaan'})
party10 = Party.create({party: 'boomerang'})
party11 = Party.create({party: 'primo-jack'})
party12 = Party.create({party: 'primo-louis'})
party13 = Party.create({party: 'prima-xanthe'})
party14 = Party.create({party: 'hhh'})
party15 = Party.create({party: 'helen'})
party16 = Party.create({party: 'storm-bonzo'})
party17 = Party.create({party: 'jules-tobes'})
party18 = Party.create({party: 'hemily'})
party19 = Party.create({party: 'jee-kee'})
party20 = Party.create({party: 'danga'})
party21 = Party.create({party: 'cedes'})
party22 = Party.create({party: 'imo-rick'})
party23 = Party.create({party: 'the-dr'})
party24 = Party.create({party: 'bobby-fagan'})
party25 = Party.create({party: 'bex'})
party26 = Party.create({party: 'millso-malcolm'})
party27 = Party.create({party: 'aj'})
party28 = Party.create({party: 'jazz'})
party29 = Party.create({party: 'phaze'})
party30 = Party.create({party: 'g-unit'})
party31 = Party.create({party: 'dv'})
party32 = Party.create({party: 'kat-jeff'})
party33 = Party.create({party: 'georgie'})
party34 = Party.create({party: 'alice-kenny'})
party35 = Party.create({party: 'bianca'})
party36 = Party.create({party: 'alidd'})
party37 = Party.create({party: 'ashi'})
party38 = Party.create({party: 'robbie'})
party39 = Party.create({party: 'paul'})
party40 = Party.create({party: 'kim'})
party41 = Party.create({party: 'trine'})
party42 = Party.create({party: 'emily-s'})
party43 = Party.create({party: 'phee'})
party44 = Party.create({party: 'campbell-smith'})
party45 = Party.create({party: 'derek-carol'})
party46 = Party.create({party: 'elizabeth'})
party47 = Party.create({party: 'sivman'})
party48 = Party.create({party: 'ria'})
party49 = Party.create({party: 'mumndad'})
party50 = Party.create({party: 'gangaba'})
party51 = Party.create({party: 's-club'})
party52 = Party.create({party: 'bhais'})
party53 = Party.create({party: 'sangash'})
party54 = Party.create({party: 'lil-baby-marley'})
party55 = Party.create({party: 'kz-myrts'})
party56 = Party.create({party: 'aneirander'})
party57 = Party.create({party: 'mw'})
party58 = Party.create({party: 'rafa'})
party59 = Party.create({party: 'chives'})
party60 = Party.create({party: 'dintendo-lucy'})
party61 = Party.create({party: 'ali-alice'})
party62 = Party.create({party: 'vig'})
party63 = Party.create({party: 'future-goslings'})
party64 = Party.create({party: 'roger-rabbits'})
party65 = Party.create({party: 'the-gomp'})
party66 = Party.create({party: 'henny-g'})
party67 = Party.create({party: 'jack-the-mack'})
party68 = Party.create({party: 'rooooobs'})
party69 = Party.create({party: 'riz'})
party70 = Party.create({party: 'lisha'})
party71 = Party.create({party: 'anish'})
party72 = Party.create({party: 'zubin-lena'})
party73 = Party.create({party: 'kaj-mike'})
party74 = Party.create({party: 'el'})
party2.guests.create({first_name: 'Olivia', last_name: 'Salter-Patel'})
party2.guests.create({first_name: 'Arav', last_name: 'Salter-Patel'})
party3.guests.create({first_name: 'Caroline', last_name: 'Salter'})
party4.guests.create({first_name: 'Josh', last_name: 'Herbert'})
party4.guests.create({first_name: 'Roxane', last_name: 'Eddings'})
party5.guests.create({first_name: 'Lara', last_name: 'Chivers'})
party5.guests.create({first_name: 'Craig', last_name: 'Chivers'})
party5.guests.create({first_name: 'Leo', last_name: 'Chivers'})
party5.guests.create({first_name: 'Freya', last_name: 'Chivers'})
party6.guests.create({first_name: 'Grandpa ', last_name: 'Salter'})
party6.guests.create({first_name: 'Grandmother', last_name: 'Salter'})
party7.guests.create({first_name: 'Charles', last_name: 'Salter'})
party7.guests.create({first_name: 'Smita ', last_name: 'Patel'})
party8.guests.create({first_name: 'Claire ', last_name: 'Salter'})
party9.guests.create({first_name: 'Yeesaan', last_name: 'Chin'})
party10.guests.create({first_name: 'Zuleika', last_name: 'Salter'})
party10.guests.create({first_name: 'Charlie', last_name: 'Schwartz'})
party10.guests.create({first_name: 'Leila', last_name: 'McCarthy'})
party10.guests.create({first_name: 'Zak', last_name: 'Schwartz'})
party11.guests.create({first_name: 'Jack', last_name: 'Salter'})
party12.guests.create({first_name: 'Louis', last_name: 'Salter'})
party13.guests.create({first_name: 'Xanthe ', last_name: 'Salter'})
party14.guests.create({first_name: 'Harold', last_name: 'Salter'})
party14.guests.create({first_name: 'Sophie', last_name: 'Brown'})
party14.guests.create({first_name: 'Felix ', last_name: 'Salter'})
party15.guests.create({first_name: 'Helen ', last_name: 'Sonn'})
party16.guests.create({first_name: 'Tash ', last_name: 'Jones'})
party16.guests.create({first_name: 'Ben', last_name: 'Powell'})
party17.guests.create({first_name: 'Juliet', last_name: 'Mitchell'})
party17.guests.create({first_name: 'Toby', last_name: 'Mitchell'})
party18.guests.create({first_name: 'Emily', last_name: 'Fu'})
party18.guests.create({first_name: 'Henry', last_name: 'Fu'})
party19.guests.create({first_name: 'Jack ', last_name: 'Eldor-Evans'})
party19.guests.create({first_name: 'Kjell', last_name: 'Eldor-Evans'})
party20.guests.create({first_name: 'Dan', last_name: 'Oldfield'})
party20.guests.create({first_name: 'Ganga', last_name: 'Shreedhar'})
party21.guests.create({first_name: 'Mercedes', last_name: 'Malcome'})
party22.guests.create({first_name: 'Imogen', last_name: 'Snell'})
party22.guests.create({first_name: 'Riccardo', last_name: 'Castano'})
party23.guests.create({first_name: 'Andreea', last_name: 'Ulcica'})
party24.guests.create({first_name: 'Kiara', last_name: 'De Vries'})
party24.guests.create({first_name: 'Steph', last_name: 'De Vries'})
party25.guests.create({first_name: 'Bekkie', last_name: 'Wetz'})
party25.guests.create({first_name: 'Michiel', last_name: 'Plantin'})
party26.guests.create({first_name: 'Camilla', last_name: 'Atkins'})
party26.guests.create({first_name: 'Malcolm', last_name: 'Pepin'})
party27.guests.create({first_name: 'Alex', last_name: 'Janczenia'})
party27.guests.create({first_name: 'Jeremy', last_name: 'Davis'})
party28.guests.create({first_name: 'Jazz', last_name: 'Kain'})
party29.guests.create({first_name: 'Ads', last_name: 'Wilson'})
party30.guests.create({first_name: 'Graeme', last_name: 'Abbot'})
party30.guests.create({first_name: 'Yolanda', last_name: "O'Leary"})
party31.guests.create({first_name: 'Tom', last_name: 'De Vries'})
party31.guests.create({first_name: 'Patty', last_name: 'De Vries'})
party32.guests.create({first_name: 'Kat', last_name: 'Thomas'})
party32.guests.create({first_name: 'Jeff', last_name: 'Shepard'})
party33.guests.create({first_name: 'Georgie', last_name: 'Robinson'})
party34.guests.create({first_name: 'Alice', last_name: 'Fyfe'})
party34.guests.create({first_name: 'Kenny', last_name: 'Gaffney'})
party35.guests.create({first_name: 'Bianca', last_name: 'Swalem'})
party35.guests.create({first_name: 'Tomek', last_name: 'Dudz'})
party36.guests.create({first_name: 'Alice', last_name: 'Doyne-Ditmas'})
party37.guests.create({first_name: 'Ashok', last_name: 'Kumar'})
party38.guests.create({first_name: 'Robbie', last_name: 'Maddison'})
party39.guests.create({first_name: 'Paul', last_name: 'Oldfield'})
party40.guests.create({first_name: 'Kim ', last_name: 'Lodge'})
party41.guests.create({first_name: 'Trine', last_name: 'Haaland Danjalsson'})
party41.guests.create({first_name: 'Danjal', last_name: 'Danjalsson'})
party42.guests.create({first_name: 'Emily', last_name: 'Sunderland'})
party43.guests.create({first_name: 'Phee', last_name: 'Doubleday'})
party44.guests.create({first_name: 'Charlie', last_name: 'Campbell-Smith'})
party44.guests.create({first_name: 'Andra', last_name: 'Campbell-Smith'})
party45.guests.create({first_name: 'Derek', last_name: 'Salter'})
party45.guests.create({first_name: 'Carol', last_name: 'Salter'})
party46.guests.create({first_name: 'Elisabeth', last_name: 'Salter-Green'})
party47.guests.create({first_name: 'Sivan', last_name: 'Patel'})
party48.guests.create({first_name: 'Ria', last_name: 'Patel'})
party49.guests.create({first_name: 'Mum', last_name: 'Patel'})
party49.guests.create({first_name: 'Dad', last_name: 'Patel'})
party50.guests.create({first_name: 'GangaBa', last_name: 'Patel'})
party51.guests.create({first_name: 'Nikunj', last_name: 'Patel'})
party51.guests.create({first_name: 'Urusha', last_name: 'Patel'})
party51.guests.create({first_name: 'Seve', last_name: 'Patel'})
party51.guests.create({first_name: 'Soren', last_name: 'Patel'})
party52.guests.create({first_name: 'Heman', last_name: 'Patel'})
party52.guests.create({first_name: 'Priya', last_name: 'Patel'})
party52.guests.create({first_name: 'Shaan', last_name: 'Patel'})
party52.guests.create({first_name: 'Sheel', last_name: 'Patel'})
party53.guests.create({first_name: 'Sangifoi', last_name: 'Sharma-Patel'})
party53.guests.create({first_name: 'Ash', last_name: 'Sharma'})
party53.guests.create({first_name: 'Kashif', last_name: 'Sharma-Patel'})
party53.guests.create({first_name: 'Anoukha', last_name: ''})
party53.guests.create({first_name: 'Shefali', last_name: 'Sharma-Patel'})
party54.guests.create({first_name: 'Jack', last_name: 'Harper'})
party54.guests.create({first_name: 'Lil', last_name: 'Harper'})
party55.guests.create({first_name: 'KZ', last_name: 'Zarbalian'})
party55.guests.create({first_name: 'Myrto', last_name: 'Mavratos'})
party56.guests.create({first_name: 'Alex', last_name: 'Temple'})
party56.guests.create({first_name: 'Aneira', last_name: 'Roose-Mclew'})
party57.guests.create({first_name: 'Matt', last_name: 'Wood'})
party58.guests.create({first_name: 'Sam', last_name: 'Stanley'})
party58.guests.create({first_name: 'Yasmin', last_name: ''})
party59.guests.create({first_name: 'Shaun', last_name: 'Lynch'})
party60.guests.create({first_name: 'Constantine', last_name: 'Samartzis'})
party60.guests.create({first_name: 'Lucy', last_name: 'Stone'})
party61.guests.create({first_name: 'Ali', last_name: 'White'})
party61.guests.create({first_name: 'Alice', last_name: 'Cazenove'})
party62.guests.create({first_name: 'Viggo', last_name: 'Blegvad'})
party63.guests.create({first_name: 'James', last_name: 'Gosling'})
party63.guests.create({first_name: 'Emily', last_name: 'Field'})
party64.guests.create({first_name: 'Jack', last_name: 'Rogers'})
party65.guests.create({first_name: 'Sam', last_name: 'Gompertz'})
party66.guests.create({first_name: 'Henry', last_name: 'Green'})
party67.guests.create({first_name: 'Jack', last_name: 'McCrae'})
party68.guests.create({first_name: 'Ruby', last_name: 'Robinson-Carver'})
party69.guests.create({first_name: 'Alex', last_name: 'Patrick'})
party70.guests.create({first_name: 'Lisha', last_name: 'Patel'})
party71.guests.create({first_name: 'Anish', last_name: 'Patel'})
party72.guests.create({first_name: 'Zubin', last_name: 'Patel'})
party72.guests.create({first_name: 'Lena', last_name: 'Patel'})
party73.guests.create({first_name: 'Kajal', last_name: 'Patel'})
party73.guests.create({first_name: 'Mike', last_name: ''})
party74.guests.create({first_name: 'El', last_name: 'Barreau'})